stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  TEST_REPORTS_DIR: tests/reports


build:
  stage: build
  script:
    - echo "Building Docker images..."
    - docker-compose build
  artifacts:
    when: always
    paths:
      - ./api-gateway
      - ./service1
      - ./service2


test:
  stage: test
  dependencies:
    - build
  script:
    - echo "Starting containers for testing..."
    - docker-compose up -d
    - echo "Running API Gateway tests..."
    - mkdir -p ${TEST_REPORTS_DIR}
    - python3 -m pytest tests/test_api_gateway.py --junitxml=${TEST_REPORTS_DIR}/test_api_gateway.xml
    - echo "Running Service1 tests..."
    - python3 -m pytest tests/test_service1.py --junitxml=${TEST_REPORTS_DIR}/test_service1.xml
    - echo "Running Service2 tests..."
    - python3 -m pytest tests/test_service2.py --junitxml=${TEST_REPORTS_DIR}/test_service2.xml
    - echo "Tearing down test containers..."
    - docker-compose down
  artifacts:
    when: always
    paths:
      - ${TEST_REPORTS_DIR}  
    reports:
      junit:
        - ${TEST_REPORTS_DIR}/test_api_gateway.xml
        - ${TEST_REPORTS_DIR}/test_service1.xml
        - ${TEST_REPORTS_DIR}/test_service2.xml


deploy:
  stage: deploy
  dependencies:
    - build
    - test
  script:
    - echo "Deploying containers..."
    - docker-compose up -d
  environment:
    name: production
    url: http://localhost:8198
  only:
    - main
    - project  