version: '3.8'

services:
  service1-1:
    build: ./service1
    depends_on:
      - service2

  service1-2:
    build: ./service1
    depends_on:
      - service2

  service1-3:
    build: ./service1
    depends_on:
      - service2

  service2:
    build: ./service2

  nginx:
    image: nginx:latest
    ports:
      - "8198:80"  # External port exposed for the system
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro  
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - api_gateway  

  api_gateway:
    build: ./api-gateway
    ports:
      - "8197:8197"  
    restart: always  
    depends_on:
      - service2